#ifndef CONFIGURATION_HPP
#define CONFIGURATION_HPP

#define DEBUG_LIN_ALG 0
#define PERFORMANCE_LEVEL 0
#define ALLOW_NEGATIVE_INDEX 0

#define ENABLE_MATRIX_MATH_FUNCTIONS 1
#define ENABLE_TENSOR_MATH_FUNCTIONS 1

#endif /* CONFIGURATION_HPP */